#  === .ENV ==========================================================
#  MONGO_DOCKER_IMAGE=mongo:5.0.9
#  MONGOEXPRESS_DOCKER_IMAGE=mongo-express:0.54.0
#  MONGO_HOST=127.0.0.1
#  MONGO_PORT=27017
#  MONGO_USERNAME=admin
#  MONGO_PASSWORD=admin
#
version: '3.1'
services:
  mongo:
    image: "${MONGO_DOCKER_IMAGE}"
    restart: always
    ports:
      - "${MONGO_HOST}:${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
  mongo-express:
    image: "${MONGOEXPRESS_DOCKER_IMAGE}"
    restart: always
    ports:
      - "127.0.0.1:27018:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_PASSWORD}"
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/"
